### ISSUE TITLE
Tudo.Issue.rummage/2 is undefined or private

### ISSUE THREAD

**Issue by Jbarget** [aditya7iyengar/rummage_phoenix#36]
`rummage_phoenix` seems to work well with version 1.0.0 but as soon as I upgrade to 1.1.0 or 1.2.0 I get an error about using `use Rummage.Ecto` in the `models` :
```
function Rummage.Ecto.__using__/1 is undefined or private
```

Changing `use` to `import` gets me passed that error but gives me:
```
function Tudo.Issue.rummage/2 is undefined or private
```

We'd like to use version 1.2 as our pagination will need to cope with a large amount of pages and therefore  we would need [maximum page links](https://github.com/aditya7iyengar/rummage_phoenix/pull/28) in `1.1.0`

Code is here: https://github.com/dwyl/tudo/tree/rummage-import

any help on direction would be great!

**Comment by jschorr** [comment]
+1

**Comment by aditya7iyengar** [comment]
Hi @Jbarget. Sorry about the delayed response. I still have to update the README and the blog to reflect new changes to `rummage`. 

I took a brief look at the code and it looks like you were importing `Rummage.Ecto` in `Tudu.Issue` module, but that doesn't define `rummage` function on `Tudo.Issue`, to be called in the controller.

The fix here is to call `Rummage.Ecto.rummage` on [this](https://github.com/dwyl/tudo/blob/rummage-import/web/controllers/issue_controller.ex#L9) line instead of `Issue.rummage`.

One of the changes I made in `rummage_ecto` was to make this call to rummage more functional looking and calling it from the `Rummage.Ecto` module itself.

**Comment by Jbarget** [comment]
Thanks for the above @aditya7iyengar,

I've managed to get v1.2.0 working but there is no `per_page` (it just lists out all of the assets). 😢 

Tried to add [these lines](https://github.com/dwyl/tudo/blob/update-rummage/config/config.exs#L36-L38) but no luck.

Am i right in thinking if we get this working the pagination elipses will be functioning as well?
