### ISSUE TITLE
Support for Phoenix 1.3 and elixir 1.5.1

### ISSUE THREAD

**Issue by devilankur18** [aditya7iyengar/rummage_phoenix#39]
Not working with current versions. Here is the error

```
== Compilation error in file lib/my_backend/segment/page_url.ex ==
** (UndefinedFunctionError) function Rummage.Ecto.__using__/1 is undefined or private
    (rummage_ecto) Rummage.Ecto.__using__([])
    lib/my_backend/segment/page_url.ex:3: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

```

Any suggestions on how to make it work ?

**Comment by thebrianemory** [comment]
I don't think your issue is related to Phoenix 1.3 and Elixir 1.5.1. I have a Phoenix 1.2.1 and Elixir 1.2 app that gets the same error with Rummage-Phoenix 1.2. I do not get the error with Rummage-Phoenix 1.0 on either version of Phoenix.

**Comment by ziazek** [comment]
I had the same issue. Found a workaround by calling `Rummage.Ecto.rummage/1` directly. e.g.

```elixir
# In the context file
# lib/app_name/company/company.ex

def list_members(rummage_params) do
  {query, r} = Member
    |> Rummage.Ecto.rummage(rummage_params)
  # IO.puts inspect(r)
  members = query
    |> Repo.all
  {members, r}
end
```

**Comment by fadzril** [comment]
Hi, guys. I've a problem getting rummage to run for phoenix 1.3. Need your help/assist

Phoenix: 1.3
Elixir: 1.5.2

Error: 
```
Failed to use "phoenix" (version 1.3.0) because
  apps/admin_web/mix.exs requires ~> 1.3.0
  apps/api/mix.exs requires ~> 1.3.0
  guardian (version 1.0.0-beta.1) requires ~> 1.0 or ~> 1.2 or ~> 1.3
  phoenix_live_reload (version 1.1.2) requires ~> 1.0 or ~> 1.2 or ~> 1.3
  phoenix_slime (version 0.8.0) requires ~> 1.2
  rummage_phoenix (version 1.2.0) requires ~> 1.2.1
```

mix.ex
`{:rummage_phoenix, "~> 1.2.0", override: true}`

**Comment by aditya7iyengar** [comment]
Hi @fadzril. Looks like you can get around it by using `{:phoenix, "~> 1.3.0", override: true}`. Full support for `phoenix 1.3` is a work in progress in #37  and #42. I have been thinking about the route  `rummage_phoenix` should take due to drastic changes in Phoenix 1.3 and expected changes in 1.4.. So, a full compatibility with phoenix 1.3 and above might take a while.. 

@devilankur18 and @thebrianemory Rummage Ecto doesn't support `__using__` macro anymore. I would recommend importing it into your ecto schema or using it like @ziazek has shown above..

I have been meaning to update rummage documentation and blogs to reflect that, but I guess I am waiting for a full compatibility with phoenix 1.3..

**Comment by fadzril** [comment]
Thanks for replying and help @aditya7iyengar . Manage to solve deps issues and encounter same problem above, I guess I should follow @ziazek steps.

Again, thanks for the help and building this. It helps a lot
